name: sanity checks on opened pull requests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'aim/sdk/**'
      - 'aim/web/api/**'
      - 'aim/storage/**'
      - '.github/workflows/pull-request.yml'
      - 'setup.py'
    types:
      - opened
      - synchronize
      - unlabeled
      - reopened
jobs:
  run-checks:
    if: ${{ ! contains(github.event.pull_request.labels.*.name, 'in progress') }}
    runs-on: ubuntu-latest
    name: Run Unit-tests, Code-style checks & Performance tests
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.dev.txt
          python -m pip install -r requirements.txt
          python -m pip install -e .
      - name: unit-tests
        run: |
          pytest --cov-report term --cov-branch --cov-fail-under=50 --cov=aim/web --cov=aim/storage --cov=aim/sdk --cov=aim/ext tests
      - name: code style checks
        run: |
          flake8 aim
      - name: configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AIM_LOGS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AIM_LOGS_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: perf tests
        run: |  # put the real perf tests script run here
          aws s3 ls s3://${{ secrets.AIM_LOGS_S3_BUCKET }}
