name: sanity checks on opened pull requests

on:
  pull_request:
    branches: main
    paths: [aim/sdk aim/web/api aim/storage]
    types: [opened, synchronize, reopened]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    name: Run Unit-tests, Code-style checks & Performance tests
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: install deps
        run: |
          python -m pip install -r requirements.dev.txt
          python -m pip install -r requirements.txt
      - name: unit-tests
        run: |
          pytest --cov-report term --cov-branch --cov-fail-under=50 --cov=aim/web --cov=aim/storage --cov=aim/sdk tests
#      - name: code style checks
#        run: |
#          flake8