name: PR naming convention verification
on:
  pull_request:
    types: [ opened, reopened, edited, ready_for_review ]
jobs:
  validate-naming-convention:
    name: Pull Request's title matches naming convention
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^\[(?:feat|fix|doc|refactor)\]\s[A-Z]'
          github_token: ${{ github.token }}
